---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    name: catalogue
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: {{ template "catalogueContainerPort" . }}
  selector:
    name: catalogue
