---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shipping
  template:
    metadata:
      labels:
        name: shipping
    spec:
      containers:
      - name: shipping
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.shipping.image.repo }}:{{ .Values.shipping.image.tag }}
        command:
        - /usr/local/bin/java.sh
        - -jar
        - ./app.jar
        - --port={{ template "shippingContainerPort" . }}
        env:
        {{- if .Values.zipkin.enabled }}
         - name: ZIPKIN
           value: {{ .Values.zipkin.urlj }}
        {{- end }}
         - name: JAVA_OPTS
           value: {{ .Values.java.options }}
        resources:
          limits:
            cpu: 300m
            memory: 2000Mi
          requests:
            cpu: 300m
            memory: 2000Mi
        ports:
        - containerPort: {{ template "shippingContainerPort" . }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: {{ template "shippingContainerPort" . }}
          initialDelaySeconds: 420
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{ template "shippingContainerPort" . }}
          initialDelaySeconds: 360
          periodSeconds: 3
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
