---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user
  labels:
    name: user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: user
    spec:
      containers:
      - name: user
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.user.image.repo }}:{{ .Values.user.image.tag }}
        resources:
          limits:
            cpu: 300m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: {{ template "userContainerPort" . }}
        env:
        - name: MONGO_HOST
          value: user-db:27017
        {{- if .Values.zipkin.enabled }}
        - name: ZIPKIN
          value: http://{{ .Values.zipkin.url }}:9411/api/v1/spans
        {{- end }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: {{ template "userContainerPort" . }}
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{ template "userContainerPort" . }}
          initialDelaySeconds: 180
          periodSeconds: 3
