{{- if .Values.zipkin.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-mysql
  labels:
    name: zipkin-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zipkin-mysql
    spec:
      containers:
      - name: zipkin-mysql
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}/{{ .Values.zipkinmysql.image.repo }}:{{ .Values.zipkinmysql.image.tag }}
        ports:
        - name: mysql
          containerPort: 3306
{{- end -}}
